window.WORDS = (window.WORDS||[]).concat([
{ unit:"D", word:"apologize", pos:"v.", ipa:"/əˈpɒlədʒaɪz/", speak:"apologize", en:"to say you are sorry for something you did wrong", zh:"道歉",
        ex1en:"He decided to apologize after sending an unkind message.", ex1zh:"他發送了一則不友善的訊息後，決定道歉。",
        ex2en:"If you hurt a classmate online, you should apologize face to face.", ex2zh:"如果你在網上傷害了同學，應該當面道歉。" },
{ unit:"D", word:"assist", pos:"v./n.", ipa:"/əˈsɪst/", speak:"assist", en:"to help; help that is given", zh:"協助；幫助",
        ex1en:"The IT teacher will assist us if we cannot log in.", ex1zh:"如果我們無法登入，資訊科技老師會協助我們。",
        ex2en:"With the assist of her friend, she reported the fake account.", ex2zh:"在朋友的協助下，她舉報了那個假帳戶。" },
{ unit:"D", word:"attack", pos:"v./n.", ipa:"/əˈtæk/", speak:"attack", en:"to try to hurt someone or something; a harmful action", zh:"攻擊",
        ex1en:"Hackers may attack a website to steal users' data.", ex1zh:"黑客可能會攻擊網站以竊取用戶資料。",
        ex2en:"The school blocked the virus after the cyber attack last week.", ex2zh:"上星期網絡攻擊發生後，學校封鎖了該病毒。" },
{ unit:"D", word:"assume", pos:"v.", ipa:"/əˈsjuːm/", speak:"assume", en:"to believe something is true without being sure", zh:"假設；以為",
        ex1en:"Do not assume that a friendly online stranger is telling the truth.", ex1zh:"不要以為網上友善的陌生人一定在說真話。",
        ex2en:"I assumed the email was from the school, but it was a scam.", ex2zh:"我以為那封電郵來自學校，但其實是騙局。" },
{ unit:"D", word:"deliver", pos:"v.", ipa:"/dɪˈlɪvə/", speak:"deliver", en:"to take something to a person or place; to give a speech", zh:"送遞；發表",
        ex1en:"The postman will deliver the new textbooks tomorrow.", ex1zh:"郵差明天會把新課本送遞過來。",
        ex2en:"She will deliver a short talk on privacy in the assembly.", ex2zh:"她將在週會上就私隱議題發表簡短演講。" },
{ unit:"D", word:"disappear", pos:"v.", ipa:"/ˌdɪsəˈpɪə/", speak:"disappear", en:"to become impossible to see or find", zh:"消失",
        ex1en:"Messages on some apps disappear after a few seconds.", ex1zh:"有些應用程式上的訊息會在數秒後消失。",
        ex2en:"His confidence did not disappear after the first mistake.", ex2zh:"第一次出錯後，他的信心並沒有消失。" },
{ unit:"D", word:"forget", pos:"v.", ipa:"/fəˈɡet/", speak:"forget", en:"to fail to remember", zh:"忘記",
        ex1en:"Don't forget to log out when you use a shared computer.", ex1zh:"使用共用電腦時，不要忘記登出。",
        ex2en:"I always forget new passwords if I do not write a hint.", ex2zh:"如果我不寫提示，我總是會忘記新密碼。" },
{ unit:"D", word:"hire", pos:"v.", ipa:"/ˈhaɪə/", speak:"hire", en:"to give someone a job; to pay to use something for a short time", zh:"聘請；僱用",
        ex1en:"The company will hire students to test a new learning app.", ex1zh:"那間公司會聘請學生測試一個新的學習應用程式。",
        ex2en:"We can hire a coach if we want extra help before the exam.", ex2zh:"如果考試前想得到額外幫助，我們可以僱用一位補習老師。" },
{ unit:"D", word:"interpret", pos:"v.", ipa:"/ɪnˈtɜːprɪt/", speak:"interpret", en:"to explain the meaning of something; to change spoken words into another language", zh:"詮釋；口譯",
        ex1en:"It is easy to interpret a short text message in the wrong way.", ex1zh:"短訊很容易被錯誤詮釋。",
        ex2en:"A classmate helped interpret the English video for her parents.", ex2zh:"一位同學幫忙為她的父母口譯那段英文影片。" },
{ unit:"D", word:"permission", pos:"n.", ipa:"/pəˈmɪʃn/", speak:"permission", en:"the act of allowing someone to do something", zh:"准許；許可",
        ex1en:"You need your parents' permission before creating a social media account.", ex1zh:"開設社交媒體帳戶前，你需要得到父母的准許。",
        ex2en:"The teacher gave us permission to use our phones for the project.", ex2zh:"老師准許我們為專題研習使用手機。" },
{ unit:"D", word:"persuade", pos:"v.", ipa:"/pəˈsweɪd/", speak:"persuade", en:"to make someone agree to do something by giving reasons", zh:"說服",
        ex1en:"Scammers try to persuade people to click a dangerous link.", ex1zh:"騙子試圖說服人們點擊危險的連結。",
        ex2en:"I persuaded my brother to turn off his phone an hour before bed.", ex2zh:"我說服弟弟在睡覺前一小時關掉手機。" },
{ unit:"D", word:"pretend", pos:"v.", ipa:"/prɪˈtend/", speak:"pretend", en:"to act as if something is true when it is not", zh:"假裝",
        ex1en:"Some people pretend to be teenagers in order to chat with students.", ex1zh:"有些人假裝自己是青少年，以便與學生聊天。",
        ex2en:"Do not pretend you understand if you need the teacher to explain again.", ex2zh:"如果你需要老師再解釋一次，不要假裝自己已經明白。" },
{ unit:"D", word:"protect", pos:"v.", ipa:"/prəˈtekt/", speak:"protect", en:"to keep someone or something safe from harm", zh:"保護",
        ex1en:"A screen lock can protect the photos on your smartphone.", ex1zh:"螢幕鎖定可以保護智能手機裡的照片。",
        ex2en:"We should protect younger students from unkind online comments.", ex2zh:"我們應該保護低年級同學，避免他們受到不友善的網上評論傷害。" },
{ unit:"D", word:"rely", pos:"v.", ipa:"/rɪˈlaɪ/", speak:"rely", en:"to need someone or something and trust that they will help", zh:"依靠；依賴",
        ex1en:"Do not rely on only one source when you read news online.", ex1zh:"在網上閱讀新聞時，不要只依靠單一來源。",
        ex2en:"She can rely on her best friend to keep a secret.", ex2zh:"她可以依靠最好的朋友保守秘密。" },
{ unit:"D", word:"remove", pos:"v.", ipa:"/rɪˈmuːv/", speak:"remove", en:"to take something away", zh:"移除；去掉",
        ex1en:"Remove apps that you no longer use to keep your phone faster.", ex1zh:"移除不再使用的應用程式，可以令手機運作更快。",
        ex2en:"Please remove your name from any photo before you post it.", ex2zh:"發佈照片前，請先去掉照片中的姓名資料。" },
{ unit:"D", word:"respect", pos:"v.", ipa:"/rɪˈspekt/", speak:"respect", en:"to treat someone or something as important and valuable", zh:"尊重",
        ex1en:"We should respect other people's opinions in a class chat.", ex1zh:"在班上的聊天中，我們應該尊重他人的意見。",
        ex2en:"Please respect your classmates' privacy and do not share their photos.", ex2zh:"請尊重同學的私隱，不要分享他們的照片。" },
{ unit:"D", word:"steal", pos:"v.", ipa:"/stiːl/", speak:"steal", en:"to take something that is not yours without permission", zh:"偷；盜取",
        ex1en:"Criminals may steal your identity if your password is too weak.", ex1zh:"如果你的密碼太弱，罪犯可能會盜取你的身分。",
        ex2en:"It is wrong to steal someone else's homework and call it your own.", ex2zh:"偷取別人的功課並當成自己的是不對的。" },
{ unit:"D", word:"threaten", pos:"v.", ipa:"/ˈθretn/", speak:"threaten", en:"to say that you will hurt someone if they do not do what you want", zh:"威脅",
        ex1en:"If anyone threatens you online, save the messages and tell an adult.", ex1zh:"如果有人在網上威脅你，請保存訊息並告訴大人。",
        ex2en:"The pop-up ad tried to threaten users by saying their files would be deleted.", ex2zh:"那個彈出廣告試圖威脅用戶，聲稱他們的檔案會被刪除。" }
]);
