window.WORDS = (window.WORDS||[]).concat([
{ unit:"C", word:"article", pos:"n.", ipa:"/ˈɑːtɪkl/", speak:"article", en:"a piece of writing in a newspaper, magazine or website", zh:"文章",
        ex1en:"I read an article about how teenagers use social media.", ex1zh:"我讀了一篇關於青少年如何使用社交媒體的文章。",
        ex2en:"Please write a short article on online safety for the school magazine.", ex2zh:"請為校刊寫一篇關於網上安全的短文。" },
{ unit:"C", word:"message", pos:"n.", ipa:"/ˈmesɪdʒ/", speak:"message", en:"information that one person sends to another", zh:"訊息；信息",
        ex1en:"Do not reply to a message from someone you do not know.", ex1zh:"不要回覆陌生人傳來的訊息。",
        ex2en:"Mum sent me a message to remind me to bring my PE kit.", ex2zh:"媽媽傳訊息提醒我帶體育課用品。" },
{ unit:"C", word:"favourite", pos:"adj.", ipa:"/ˈfeɪvərɪt/", speak:"favourite", audioUS:"favorite", en:"liked more than anything or anyone else", zh:"最喜愛的",
        ex1en:"English is my favourite subject because I enjoy reading stories.", ex1zh:"英文是我最喜愛的科目，因為我喜歡閱讀故事。",
        ex2en:"What is your favourite app for learning new words?", ex2zh:"你最喜愛用來學習新詞的應用程式是哪一個？" },
{ unit:"C", word:"secret", pos:"n.", ipa:"/ˈsiːkrət/", speak:"secret", en:"something that you do not want other people to know", zh:"秘密",
        ex1en:"A password is a secret and you should not tell it to classmates.", ex1zh:"密碼是秘密，你不應告訴同學。",
        ex2en:"She kept her birthday plan a secret until the party started.", ex2zh:"她把生日計劃當成秘密，直到派對開始才揭曉。" },
{ unit:"C", word:"knowledge", pos:"n.", ipa:"/ˈnɒlɪdʒ/", speak:"knowledge", en:"what you know from learning or experience", zh:"知識",
        ex1en:"Good knowledge of online risks can keep you safer.", ex1zh:"具備良好的網上風險知識可以令你更安全。",
        ex2en:"The more knowledge you have, the easier it is to spot fake news.", ex2zh:"你擁有的知識越多，就越容易辨認假新聞。" },
{ unit:"C", word:"financial", pos:"adj./n.", ipa:"/faɪˈnænʃl/", speak:"financial", en:"connected with money; money matters", zh:"財務的；金融的；財務事宜",
        ex1en:"Never give your financial details, such as bank numbers, to a stranger.", ex1zh:"千萬不要把財務資料（例如銀行號碼）給陌生人。",
        ex2en:"The article explained the financial problems caused by online shopping scams.", ex2zh:"那篇文章解釋了網上購物騙案所引起的財務問題。" },
{ unit:"C", word:"employer", pos:"n.", ipa:"/ɪmˈplɔɪə/", speak:"employer", en:"a person or company that pays people to work", zh:"僱主",
        ex1en:"Your future employer may look at your public social media pages.", ex1zh:"你未來的僱主可能會查看你公開的社交媒體頁面。",
        ex2en:"The employer asked the students to send a polite email, not a casual chat.", ex2zh:"僱主要求學生發送一封有禮的電郵，而不是隨便聊天。" },
{ unit:"C", word:"criticism", pos:"n.", ipa:"/ˈkrɪtɪsɪzəm/", speak:"criticism", en:"remarks that say what is wrong with something", zh:"批評",
        ex1en:"Kind criticism from a teacher can help you improve your writing.", ex1zh:"老師善意的批評可以幫助你改善寫作。",
        ex2en:"Online criticism can be hurtful if people hide behind fake names.", ex2zh:"如果人們用假名隱藏身分，網上批評可能會令人受傷。" },
{ unit:"C", word:"gesture", pos:"n.", ipa:"/ˈdʝestʃə/", speak:"gesture", en:"a movement of the hand or body that shows a feeling or idea", zh:"手勢；姿態",
        ex1en:"A thumbs-up gesture in a video call means you agree.", ex1zh:"視像通話中竪起拇指的手勢表示你同意。",
        ex2en:"Sending a thank-you card is a kind gesture after someone helps you.", ex2zh:"別人幫助你之後，寄一張感謝卡是一種友善的姿態。" },
{ unit:"C", word:"chat", pos:"v./n.", ipa:"/tʃæt/", speak:"chat", en:"to talk in a friendly way; a friendly talk", zh:"聊天；閑談",
        ex1en:"We chat with our groupmates on the class app after school.", ex1zh:"放學後我們會在班上的應用程式與組員聊天。",
        ex2en:"A short chat with the teacher helped her understand the homework.", ex2zh:"與老師短暫閑談後，她明白了功課的要求。" }
]);
