window.WORDS = (window.WORDS||[]).concat([
{ unit:"E", word:"afraid", pos:"adj.", ipa:"/əˈfreɪd/", speak:"afraid", en:"feeling fear; worried that something bad may happen", zh:"害怕的；擔心的",
        ex1en:"She was afraid to click the strange link in the email.", ex1zh:"她害怕點擊電郵裡那個奇怪的連結。",
        ex2en:"Don't be afraid to ask for help if a message makes you uncomfortable.", ex2zh:"如果一則訊息令你感到不舒服，不要害怕求助。" },
{ unit:"E", word:"aware", pos:"adj.", ipa:"/əˈweə/", speak:"aware", en:"knowing that something exists or is happening", zh:"意識到的；知道的",
        ex1en:"Students should be aware of the risks of talking to strangers online.", ex1zh:"學生應該意識到與網上陌生人交談的風險。",
        ex2en:"He was not aware that his location was shared with the app.", ex2zh:"他不知道自己的位置已被該應用程式分享。" },
{ unit:"E", word:"completely", pos:"adv.", ipa:"/kəmˈpliːtli/", speak:"completely", en:"in every way; totally", zh:"完全地",
        ex1en:"The rumour was completely false, so we ignored it.", ex1zh:"那個謠言完全是假的，所以我們不予理會。",
        ex2en:"Please turn your phone completely off before the examination begins.", ex2zh:"考試開始前，請把手機完全關掉。" },
{ unit:"E", word:"emergency", pos:"n.", ipa:"/ɪˈmɜːdʒənsi/", speak:"emergency", en:"a sudden and dangerous situation that needs quick action", zh:"緊急情況",
        ex1en:"In an emergency, call 999 and tell them your location clearly.", ex1zh:"遇到緊急情況時，請致999並清楚說明你的位置。",
        ex2en:"Keep a parent's number on paper in case of a phone emergency.", ex2zh:"以防手機出現緊急情況，請把家長電話寫在紙上。" },
{ unit:"E", word:"emotion", pos:"n.", ipa:"/ɪˈməʊʃn/", speak:"emotion", en:"a strong feeling such as happiness, anger or fear", zh:"情緒；情感",
        ex1en:"It is better not to post when a strong emotion makes you angry.", ex1zh:"當強烈情緒令你生氣時，最好不要發佈內容。",
        ex2en:"A kind message can change a classmate's emotion after a hard day.", ex2zh:"一句善意的訊息可以在同學辛苦一天後改變他的情緒。" },
{ unit:"E", word:"harm", pos:"n.", ipa:"/hɑːm/", speak:"harm", en:"damage or injury", zh:"傷害；損害",
        ex1en:"Mean comments can cause real harm even if they are only online.", ex1zh:"即使只是在網上，惡意評論也可能造成真正的傷害。",
        ex2en:"The teacher explained how to use the Internet with less harm to our eyes.", ex2zh:"老師解釋了如何使用互聯網，減少對眼睛的傷害。" },
{ unit:"E", word:"relief", pos:"n.", ipa:"/rɪˈliːf/", speak:"relief", en:"a calm or happy feeling after worry or pain has gone", zh:"寬慰；如釋重負",
        ex1en:"She felt great relief after telling her mum about the unkind messages.", ex1zh:"她把那些不友善的訊息告訴媽媽後，感到大大寬慰。",
        ex2en:"It was a relief to find that the lost phone was only in her locker.", ex2zh:"發現遺失的手機原來只是在儲物櫃裡，真是如釋重負。" },
{ unit:"E", word:"severe", pos:"adj.", ipa:"/sɪˈvɪə/", speak:"severe", en:"very serious or very bad", zh:"嚴重的",
        ex1en:"The school gave a severe warning to students who shared private photos.", ex1zh:"學校向分享私人照片的學生發出嚴重警告。",
        ex2en:"A severe password leak can put many accounts in danger at the same time.", ex2zh:"一次嚴重的密碼洩漏可能同時令許多帳戶陷入危險。" }
]);
