window.WORDS = (window.WORDS||[]).concat([
{ unit:"B", word:"addiction", pos:"n.", ipa:"/əˈdɪkʃn/", speak:"addiction", en:"a strong need to do something again and again, even when it is harmful", zh:"成瘾；上瘾",
        ex1en:"Phone addiction can make it hard for students to sleep at night.", ex1zh:"手機成瘾會令學生晚上難以入睡。",
        ex2en:"He asked the teacher for help because his game addiction was getting worse.", ex2zh:"他向老師求助，因為他的遊戲成瘾情況越來越嚴重。" },
{ unit:"B", word:"hackers", pos:"n.", ipa:"/ˈhækəz/", speak:"hackers", audio:"hacker", en:"people who break into computers or accounts without permission", zh:"黑客",
        ex1en:"Hackers tried to steal passwords from the school email system.", ex1zh:"黑客試圖從學校電郵系統偷取密碼。",
        ex2en:"Strong passwords can stop most hackers from entering your account.", ex2zh:"強密碼可以阻止大部分黑客進入你的帳戶。" },
{ unit:"B", word:"identity", pos:"n.", ipa:"/aɪˈdentəti/", speak:"identity", en:"who a person is; the facts that show a person is himself or herself", zh:"身分；身份",
        ex1en:"Never share your identity details, such as your ID number, online.", ex1zh:"千萬不要在網上分享你的身分資料，例如身份證號碼。",
        ex2en:"Someone used her identity to open a fake social media account.", ex2zh:"有人用她的身分開了一個假的社交媒體帳戶。" },
{ unit:"B", word:"online", pos:"adj.", ipa:"/ˌɒnˈlaɪn/", speak:"online", en:"connected to the Internet", zh:"網上的；線上的",
        ex1en:"Many S2 students do online homework after school.", ex1zh:"許多中二學生放學後會做網上功課。",
        ex2en:"Online shopping is quick, but you must check if the shop is real.", ex2zh:"網上購物很快捷，但你必須檢查該商店是否真實。" },
{ unit:"B", word:"podcast", pos:"n.", ipa:"/ˈpɒdkɑːst/", speak:"podcast", en:"a spoken programme you can listen to on a phone or computer", zh:"播客",
        ex1en:"Our English teacher asked us to listen to a short news podcast.", ex1zh:"英文老師要求我們聽一段簡短的新聞播客。",
        ex2en:"I learn new words faster when I listen to a science podcast on the bus.", ex2zh:"我在巴士上聽科學播客時，學新詞會更快。" },
{ unit:"B", word:"privacy", pos:"n.", ipa:"/ˈprɪvəsi/", speak:"privacy", en:"the right to keep your personal information and life private", zh:"私隱",
        ex1en:"Closing the location setting on your phone protects your privacy.", ex1zh:"關閉手機的定位設定可以保護你的私隱。",
        ex2en:"Posting your home address online is bad for your privacy.", ex2zh:"在網上張貼家中地址對你的私隱不利。" },
{ unit:"B", word:"radiation", pos:"n.", ipa:"/ˌreɪdɪˈeɪʃn/", speak:"radiation", en:"energy that comes from something such as the sun, X-rays or some devices", zh:"輻射",
        ex1en:"Some people worry about radiation from using a phone for too long.", ex1zh:"有些人擔心長時間使用手機所產生的輻射。",
        ex2en:"The scientist explained that sunlight also gives off radiation.", ex2zh:"那位科學家解釋，陽光也會放出輻射。" },
{ unit:"B", word:"scientist", pos:"n.", ipa:"/ˈsaɪəntɪst/", speak:"scientist", en:"a person who studies nature or technology through research", zh:"科學家",
        ex1en:"A scientist spoke to our class about staying safe on the Internet.", ex1zh:"一位科學家向我們班講解如何在互聯網上保持安全。",
        ex2en:"The young scientist invented an app that blocks dangerous websites.", ex2zh:"那位年輕科學家發明了一個可以封鎖危險網站的應用程式。" },
{ unit:"B", word:"trace", pos:"n.", ipa:"/treɪs/", speak:"trace", en:"a small sign that someone or something was there", zh:"痕跡；蹤跡",
        ex1en:"Every click you make can leave a trace on the Internet.", ex1zh:"你每次點擊都可能在互聯網上留下痕跡。",
        ex2en:"The police found no trace of the stolen laptop in the classroom.", ex2zh:"警方在課室裡找不到被偷手提電腦的任何蹤跡。" },
{ unit:"B", word:"victim", pos:"n.", ipa:"/ˈvɪktɪm/", speak:"victim", en:"a person who is hurt, tricked or attacked", zh:"受害者",
        ex1en:"The victim of the online scam lost all the money in her account.", ex1zh:"這宗網上騙案的受害者失去了帳戶裡所有的錢。",
        ex2en:"If you become a victim of cyberbullying, tell a teacher at once.", ex2zh:"如果你成為網絡欺凌的受害者，應立刻告訴老師。" }
]);
